'use client';

import { useEffect, useMemo, useState } from 'react';
import type { CallToolResponse } from '@nitrostack/widgets';
import type { DashboardField, DashboardTool } from './tool-catalog';

type Dict = Record<string, any>;
type CallTool = (name: string, args?: Dict) => Promise<CallToolResponse>;

function resultData(result: any): Dict { if (result?.structuredContent && typeof result.structuredContent === 'object') return result.structuredContent; const text = result?.content?.find((item: any) => item?.type === 'text')?.text; try { return text ? JSON.parse(text) : result ?? {}; } catch { return result ?? {}; } }
function isError(value: Dict) { return value.ok === false || Boolean(value.code); }
function safeDetails(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(safeDetails);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(Object.entries(value as Dict).filter(([key]) => !/(token|secret|authorization|bearer|api[_-]?key|code[_-]?verifier|state)/i.test(key)).map(([key, item]) => [key, safeDetails(item)]));
}

function Field({ field, value, onChange }: { field: DashboardField; value: string | number | boolean | undefined; onChange: (value: string | number | boolean) => void }) {
  const common = { id: `dashboard-${field.name}`, name: field.name, placeholder: field.placeholder, 'aria-label': field.label };
  return <label className="mcp-field"><span>{field.label}{field.required ? <em> *</em> : null}</span>{field.type === 'textarea' ? <textarea {...common} value={String(value ?? '')} onChange={(event) => onChange(event.target.value)} rows={3} /> : field.type === 'toggle' ? <input {...common} type="checkbox" checked={Boolean(value)} onChange={(event) => onChange(event.target.checked)} /> : field.type === 'number' ? <input {...common} type="number" value={value === undefined ? '' : String(value)} onChange={(event) => onChange(event.target.value === '' ? '' : Number(event.target.value))} /> : field.type === 'select' ? <select {...common} value={String(value ?? '')} onChange={(event) => onChange(event.target.value)}>{field.options?.map((option) => <option key={option} value={option}>{option}</option>)}</select> : <input {...common} type="text" value={String(value ?? '')} onChange={(event) => onChange(event.target.value)} />}{field.description && <small>{field.description}</small>}</label>;
}

export function ToolDrawer({ tool, onClose, callTool, openExternal }: { tool: DashboardTool; onClose: () => void; callTool: CallTool; openExternal: (url: string) => void }) {
  const initial = useMemo(() => Object.fromEntries(tool.fields.filter((field) => field.defaultValue !== undefined).map((field) => [field.name, field.defaultValue])), [tool]);
  const [values, setValues] = useState<Dict>(initial);
  const [output, setOutput] = useState<Dict | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { setValues(initial); setOutput(null); setError(''); }, [initial]);
  const run = async () => { setBusy(true); setError(''); setOutput(null); const args: Dict = {}; for (const field of tool.fields) { const value = values[field.name]; if (value === '' || value === undefined || value === false && field.type !== 'toggle') continue; if (field.name === 'keywords' || field.name === 'hashtags') args[field.name] = String(value).split(',').map((item) => item.trim()).filter(Boolean); else if (field.name === 'conversation' || field.name === 'topicSample' || field.name === 'constraints' || field.name === 'topics') args[field.name] = String(value).split(/[\n,]/).map((item) => item.trim()).filter(Boolean); else args[field.name] = value; } const requiredMissing = tool.fields.filter((field) => field.required && (args[field.name] === undefined || args[field.name] === '')).map((field) => field.label); if (requiredMissing.length) { setError(`Required: ${requiredMissing.join(', ')}`); setBusy(false); return; } if ((tool.name === 'x_get_user' || ['x_get_user_posts', 'x_get_followers', 'x_get_following', 'x_get_mentions'].includes(tool.name)) && Boolean(args.id || args.userId) === Boolean(args.username)) { setError('Provide exactly one identity: username or numeric user ID.'); setBusy(false); return; } if ((args.id && !/^\d+$/.test(String(args.id))) || (args.userId && !/^\d+$/.test(String(args.userId)))) { setError('User ID must be numeric. Use the username field for handles.'); setBusy(false); return; } try { const result = await callTool(tool.name, args); const data = resultData(result); if (isError(data) || result?.isError) setError(String(data.message ?? data.code ?? 'Tool request failed.')); else setOutput(data); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Tool request failed.'); } finally { setBusy(false); } };
  return <aside className="mcp-drawer" aria-label={`${tool.name} tool panel`}><div className="mcp-drawer-head"><div><span className={`mcp-kicker ${tool.category.toLowerCase()}`}>{tool.category}</span><h2>{tool.name}</h2><p>{tool.description}</p></div><button type="button" className="mcp-icon-button" onClick={onClose} aria-label="Close tool panel">×</button></div><div className="mcp-drawer-scroll">{tool.fields.length ? <div className="mcp-form">{tool.fields.map((field) => <Field key={field.name} field={field} value={values[field.name]} onChange={(value) => setValues((current) => ({ ...current, [field.name]: value }))}/>)}</div> : <div className="mcp-empty"><strong>No arguments required</strong><span>This status tool is ready to run.</span></div>}{error && <div className="mcp-alert" role="alert">{error}</div>}<button type="button" className="mcp-primary-button" onClick={() => void run()} disabled={busy}>{busy ? 'Executing…' : 'Run real tool'}</button>{output && <ToolOutput data={output} tool={tool} callTool={callTool} openExternal={openExternal}/>}</div></aside>;
}

function ToolOutput({ data, tool, callTool, openExternal }: { data: Dict; tool: DashboardTool; callTool: CallTool; openExternal: (url: string) => void }) {
  const user = data.user ?? data;
  const posts = Array.isArray(data.data) ? data.data : [];
  const draft = data.draft ?? data.improvedDraft;
  return <section className="mcp-output"><div className="mcp-output-head"><span>LIVE RESULT</span><b>{tool.name}</b></div>{draft && <><div className="mcp-draft-box">{String(draft)}</div><div className="mcp-output-meta"><span>Characters {String(String(draft).length)}</span><span>{String(data.provider ?? 'AI')}</span><span>{data.grounded === true ? 'Grounded' : 'User input'}</span></div><div className="mcp-actions"><button type="button" className="mcp-secondary-button" onClick={() => void navigator.clipboard?.writeText(String(draft))}>Copy draft</button>{tool.name !== 'x_improve_post' && <button type="button" className="mcp-secondary-button" onClick={() => void callTool('x_improve_post', { text: String(draft), suggestHashtags: true })}>Improve draft</button>}</div></>}{user?.username && <div className="mcp-result-card"><div className="mcp-avatar">{String(user.name ?? user.username).slice(0, 1)}</div><div><strong>{String(user.name ?? 'X user')}</strong><span>@{String(user.username)}</span><p>{String(user.bio ?? 'No biography returned.')}</p></div><button type="button" className="mcp-secondary-button" onClick={() => openExternal(`https://x.com/${encodeURIComponent(String(user.username))}`)}>Open X</button></div>}{data.overallSentiment && <div className="mcp-sentiment"><strong>{String(data.overallSentiment)}</strong><span>Confidence {Math.round(Number(data.confidence ?? 0) * 100)}%</span><p>{String(data.explanation ?? '')}</p></div>}{posts.length > 0 && <div className="mcp-mini-list">{posts.slice(0, 5).map((post: any, index: number) => <div key={String(post.id ?? index)}><span>{String(post.author?.username ?? post.authorId ?? 'account')}</span><p>{String(post.text ?? 'No text')}</p></div>)}</div>}<details className="mcp-details"><summary>Developer details</summary><pre>{JSON.stringify(safeDetails(data), null, 2)}</pre></details></section>;
}
