export type DashboardField = {
  name: string;
  label: string;
  type: 'text' | 'number' | 'textarea' | 'toggle' | 'select';
  required?: boolean;
  placeholder?: string;
  description?: string;
  options?: string[];
  defaultValue?: string | number | boolean;
};

export type DashboardTool = {
  name: string;
  category: 'READ' | 'AI' | 'STATUS';
  description: string;
  fields: DashboardField[];
  presentation: string;
};

/** Mirrors the current bounded DemoModule registration; calls still go through the host RPC. */
export const DEMO_TOOLS: DashboardTool[] = [
  { name: 'x_get_capabilities', category: 'STATUS', description: 'Configured X access and capability flags.', fields: [], presentation: 'Capability core' },
  { name: 'x_get_user', category: 'READ', description: 'Look up an X user by ID or username.', fields: [{ name: 'id', label: 'User ID', type: 'text', placeholder: 'Numeric X user ID' }, { name: 'username', label: 'Username', type: 'text', placeholder: 'XDevelopers or @XDevelopers', description: 'Provide exactly one of User ID or Username.' }], presentation: 'Profile telemetry' },
  { name: 'x_get_post', category: 'READ', description: 'Fetch one real X post by ID.', fields: [{ name: 'postId', label: 'Post ID', type: 'text', required: true, placeholder: 'Numeric X post ID' }], presentation: 'Post telemetry' },
  { name: 'x_search_posts', category: 'READ', description: 'Search recent public X posts.', fields: [{ name: 'query', label: 'Query', type: 'text', required: true, placeholder: 'from:XDevelopers' }, { name: 'maxResults', label: 'Max results', type: 'number', required: true, defaultValue: 10, description: 'X requires at least 10.' }, { name: 'username', label: 'Username filter', type: 'text', placeholder: 'Optional handle' }, { name: 'hashtag', label: 'Hashtag filter', type: 'text', placeholder: 'Optional hashtag' }, { name: 'language', label: 'Language', type: 'text', placeholder: 'en' }, { name: 'excludeReposts', label: 'Exclude reposts', type: 'toggle', defaultValue: false }, { name: 'excludeReplies', label: 'Exclude replies', type: 'toggle', defaultValue: false }, { name: 'startTime', label: 'Start time', type: 'text', placeholder: 'ISO 8601, optional' }, { name: 'endTime', label: 'End time', type: 'text', placeholder: 'ISO 8601, optional' }, { name: 'paginationToken', label: 'Pagination token', type: 'text', placeholder: 'Optional next token' }], presentation: 'Search telemetry' },
  { name: 'x_get_user_posts', category: 'READ', description: 'Fetch a bounded public user timeline.', fields: [{ name: 'userId', label: 'User ID', type: 'text', placeholder: 'Numeric X user ID' }, { name: 'username', label: 'Username', type: 'text', placeholder: 'XDevelopers or @XDevelopers' }, { name: 'maxResults', label: 'Max results', type: 'number', defaultValue: 10, required: true }, { name: 'paginationToken', label: 'Pagination token', type: 'text', placeholder: 'Optional next token' }], presentation: 'Timeline telemetry' },
  { name: 'x_get_followers', category: 'READ', description: 'Fetch a bounded follower page.', fields: [{ name: 'userId', label: 'User ID', type: 'text', placeholder: 'Numeric X user ID' }, { name: 'username', label: 'Username', type: 'text', placeholder: 'XDevelopers or @XDevelopers' }, { name: 'maxResults', label: 'Max results', type: 'number', defaultValue: 10, required: true }, { name: 'paginationToken', label: 'Pagination token', type: 'text', placeholder: 'Optional next token' }], presentation: 'Follower telemetry' },
  { name: 'x_get_following', category: 'READ', description: 'Fetch a bounded following page.', fields: [{ name: 'userId', label: 'User ID', type: 'text', placeholder: 'Numeric X user ID' }, { name: 'username', label: 'Username', type: 'text', placeholder: 'XDevelopers or @XDevelopers' }, { name: 'maxResults', label: 'Max results', type: 'number', defaultValue: 10, required: true }, { name: 'paginationToken', label: 'Pagination token', type: 'text', placeholder: 'Optional next token' }], presentation: 'Following telemetry' },
  { name: 'x_get_mentions', category: 'READ', description: 'Fetch posts mentioning a user.', fields: [{ name: 'userId', label: 'User ID', type: 'text', placeholder: 'Numeric X user ID' }, { name: 'username', label: 'Username', type: 'text', placeholder: 'XDevelopers or @XDevelopers' }, { name: 'maxResults', label: 'Max results', type: 'number', defaultValue: 10, required: true }, { name: 'paginationToken', label: 'Pagination token', type: 'text', placeholder: 'Optional next token' }], presentation: 'Mention telemetry' },
  { name: 'x_analyze_post', category: 'READ', description: 'Calculate deterministic engagement metrics for a real post.', fields: [{ name: 'postId', label: 'Post ID', type: 'text', required: true, placeholder: 'Numeric X post ID' }], presentation: 'Metric telemetry' },
  { name: 'x_ai_status', category: 'STATUS', description: 'Show configured AI provider state without generation.', fields: [], presentation: 'AI telemetry' },
  { name: 'x_generate_post', category: 'AI', description: 'Generate a draft only; never publish.', fields: [{ name: 'topic', label: 'Topic', type: 'textarea', required: true, placeholder: 'Why MCP servers matter' }, { name: 'goal', label: 'Goal', type: 'text', placeholder: 'Inform or engage' }, { name: 'tone', label: 'Tone', type: 'text', defaultValue: 'professional' }, { name: 'audience', label: 'Audience', type: 'text' }, { name: 'context', label: 'Context', type: 'textarea' }, { name: 'keywords', label: 'Keywords', type: 'text', description: 'Comma-separated.' }, { name: 'hashtags', label: 'Hashtags', type: 'text', description: 'Comma-separated, optional.' }, { name: 'constraints', label: 'Constraints', type: 'textarea', description: 'One per line.' }, { name: 'referenceMaterial', label: 'Reference material', type: 'textarea' }], presentation: 'Draft telemetry' },
  { name: 'x_generate_thread', category: 'AI', description: 'Generate ordered draft posts only.', fields: [{ name: 'topic', label: 'Topic', type: 'textarea', required: true }, { name: 'goal', label: 'Goal', type: 'text' }, { name: 'audience', label: 'Audience', type: 'text' }, { name: 'tone', label: 'Tone', type: 'text', defaultValue: 'professional' }, { name: 'numberOfPosts', label: 'Posts', type: 'number', defaultValue: 2, required: true }, { name: 'context', label: 'Context', type: 'textarea' }, { name: 'constraints', label: 'Constraints', type: 'textarea', description: 'One per line.' }], presentation: 'Thread draft telemetry' },
  { name: 'x_generate_reply', category: 'AI', description: 'Generate a reply draft from a real post.', fields: [{ name: 'postId', label: 'Post ID', type: 'text', placeholder: 'Numeric X post ID' }, { name: 'postText', label: 'Post text', type: 'textarea', placeholder: 'Alternative to Post ID' }, { name: 'goal', label: 'Goal', type: 'text' }, { name: 'tone', label: 'Tone', type: 'text', defaultValue: 'professional' }, { name: 'context', label: 'Context', type: 'textarea' }], presentation: 'Reply draft telemetry' },
  { name: 'x_rewrite_post', category: 'AI', description: 'Rewrite supplied text into a draft.', fields: [{ name: 'text', label: 'Text', type: 'textarea', required: true }, { name: 'goal', label: 'Goal', type: 'select', required: true, options: ['shorter', 'clearer', 'professional', 'casual', 'technical', 'engaging', 'concise', 'grammar', 'custom'], defaultValue: 'clearer' }, { name: 'customGoal', label: 'Custom goal', type: 'text' }, { name: 'preserveFacts', label: 'Preserve facts', type: 'toggle', defaultValue: true }, { name: 'context', label: 'Context', type: 'textarea' }], presentation: 'Rewrite telemetry' },
  { name: 'x_improve_post', category: 'AI', description: 'Improve supplied text into a draft.', fields: [{ name: 'text', label: 'Text', type: 'textarea', required: true }, { name: 'audience', label: 'Audience', type: 'text' }, { name: 'goal', label: 'Goal', type: 'text' }, { name: 'context', label: 'Context', type: 'textarea' }, { name: 'suggestHashtags', label: 'Suggest hashtags', type: 'toggle', defaultValue: true }], presentation: 'Improvement telemetry' },
  { name: 'x_summarize_thread', category: 'AI', description: 'Summarize a real bounded thread.', fields: [{ name: 'postId', label: 'Post ID', type: 'text', required: true }, { name: 'maxResults', label: 'Max results', type: 'number', defaultValue: 10, required: true }], presentation: 'Thread telemetry' },
  { name: 'x_summarize_conversation', category: 'AI', description: 'Summarize a real bounded conversation sample.', fields: [{ name: 'postId', label: 'Post ID', type: 'text', required: true }, { name: 'maxResults', label: 'Max results', type: 'number', defaultValue: 10, required: true }], presentation: 'Conversation telemetry' },
  { name: 'x_analyze_sentiment', category: 'AI', description: 'Analyze text sentiment only.', fields: [{ name: 'postId', label: 'Post ID', type: 'text', placeholder: 'Numeric X post ID' }, { name: 'postText', label: 'Post text', type: 'textarea', placeholder: 'Alternative text input' }, { name: 'conversation', label: 'Conversation lines', type: 'textarea', description: 'One line per item.' }, { name: 'topicSample', label: 'Topic sample', type: 'textarea', description: 'One line per item.' }], presentation: 'Sentiment telemetry' },
  { name: 'x_generate_content_ideas', category: 'AI', description: 'Generate structured ideas without publishing.', fields: [{ name: 'topic', label: 'Topic', type: 'textarea', required: true }, { name: 'audience', label: 'Audience', type: 'text' }, { name: 'goal', label: 'Goal', type: 'text' }, { name: 'numberOfIdeas', label: 'Ideas', type: 'number', defaultValue: 3, required: true }, { name: 'accountContext', label: 'Account context', type: 'textarea' }], presentation: 'Ideas telemetry' },
  { name: 'x_content_strategy', category: 'AI', description: 'Generate grounded strategy recommendations.', fields: [{ name: 'topic', label: 'Topic', type: 'text' }, { name: 'goal', label: 'Goal', type: 'textarea', required: true }, { name: 'audience', label: 'Audience', type: 'text' }, { name: 'userId', label: 'User ID', type: 'text', placeholder: 'Numeric ID for account grounding' }, { name: 'maxResults', label: 'Max results', type: 'number', defaultValue: 10, required: true }, { name: 'context', label: 'Context', type: 'textarea' }], presentation: 'Strategy telemetry' },
  { name: 'x_generate_hashtags', category: 'AI', description: 'Suggest hashtags from bounded topic signals.', fields: [{ name: 'topic', label: 'Topic', type: 'textarea', required: true }, { name: 'maxResults', label: 'Max results', type: 'number', defaultValue: 10, required: true }, { name: 'hashtags', label: 'Seed hashtags', type: 'text', description: 'Comma-separated, optional.' }], presentation: 'Hashtag telemetry' },
];

export const DEMO_RESOURCES = [
  { id: 'health://checks', label: 'Health Check', tone: 'green' },
  { id: 'ui://widget/next-dashboard.html', label: 'MCP Command Center', tone: 'purple' },
  { id: 'ui://widget/next-account-profile.html', label: 'Account Profile', tone: 'purple' },
  { id: 'ui://widget/next-post-card.html', label: 'Post Card', tone: 'purple' },
  { id: 'ui://widget/next-search-dashboard.html', label: 'Search Dashboard', tone: 'purple' },
  { id: 'ui://widget/next-analytics-dashboard.html', label: 'Analytics Dashboard', tone: 'purple' },
  { id: 'ui://widget/next-system-status.html', label: 'System Status', tone: 'purple' },
  { id: 'ui://widget/next-composer.html', label: 'Composer', tone: 'purple' },
  { id: 'widget://examples', label: 'Widget Examples', tone: 'purple' },
] as const;
