import { z } from 'zod';

const shortText = z.string().trim().min(1).max(4000);
const contextText = z.string().max(12000).optional();
const tone = z.string().trim().max(120).default('clear and useful');
const warningList = z.array(z.string().max(500)).max(20).default([]);
const hashtags = z.array(z.string().regex(/^#[A-Za-z0-9_]{1,100}$/)).max(20).default([]);

export const generatePostSchema = z.object({ topic: shortText, goal: shortText.optional(), tone, audience: z.string().max(300).optional(), context: contextText, keywords: z.array(z.string().trim().min(1).max(80)).max(20).default([]), hashtags, constraints: z.array(z.string().trim().min(1).max(300)).max(20).default([]), referenceMaterial: contextText });
export const generateThreadSchema = z.object({ topic: shortText, goal: shortText.optional(), audience: z.string().max(300).optional(), tone, numberOfPosts: z.number().int().min(2).max(20).default(3), context: contextText, constraints: z.array(z.string().trim().min(1).max(300)).max(20).default([]) });
export const generateReplySchema = z.object({ postId: z.string().regex(/^\d+$/).optional(), postText: shortText.optional(), goal: shortText.optional(), tone, context: contextText }).refine((value) => Boolean(value.postId || value.postText), 'Provide postId or postText.');
export const rewritePostSchema = z.object({ text: shortText, goal: z.enum(['shorter', 'clearer', 'professional', 'casual', 'technical', 'engaging', 'concise', 'grammar', 'custom']), customGoal: z.string().max(500).optional(), preserveFacts: z.boolean().default(true), context: contextText });
export const improvePostSchema = z.object({ text: shortText, audience: z.string().max(300).optional(), goal: shortText.optional(), context: contextText, suggestHashtags: z.boolean().default(true) });
export const threadInputSchema = z.object({ postId: z.string().regex(/^\d+$/), maxResults: z.number().int().min(10).max(100).default(30) });
export const conversationInputSchema = threadInputSchema;
export const sentimentSchema = z.object({ postText: shortText.optional(), postId: z.string().regex(/^\d+$/).optional(), conversation: z.array(shortText).max(100).optional(), topicSample: z.array(shortText).max(100).optional() }).refine((value) => Boolean(value.postText || value.postId || value.conversation?.length || value.topicSample?.length), 'Provide text, postId, conversation, or topicSample.');
export const contentIdeasSchema = z.object({ topic: shortText, audience: z.string().max(300).optional(), goal: shortText.optional(), numberOfIdeas: z.number().int().min(1).max(20).default(5), accountContext: contextText });
export const audienceSchema = z.object({ userId: z.string().regex(/^\d+$/).optional(), postTexts: z.array(shortText).max(100).optional(), maxResults: z.number().int().min(10).max(100).default(30) }).refine((value) => Boolean(value.userId || value.postTexts?.length), 'Provide userId or postTexts.');
export const trendSchema = z.object({ query: shortText, maxResults: z.number().int().min(10).max(100).default(30) });
export const strategySchema = z.object({ topic: shortText.optional(), goal: shortText, audience: z.string().max(300).optional(), userId: z.string().regex(/^\d+$/).optional(), maxResults: z.number().int().min(10).max(100).default(30), context: contextText });
export const hashtagSuggestionSchema = z.object({ topic: shortText, maxResults: z.number().int().min(10).max(100).default(30), hashtags: z.array(z.string().trim().min(1).max(100)).max(20).default([]) });
export const calendarSchema = z.object({ goal: shortText, topics: z.array(shortText).min(1).max(20), days: z.number().int().min(1).max(31).default(7), postsPerDay: z.number().int().min(1).max(5).default(1), audience: z.string().max(300).optional(), userId: z.string().regex(/^\d+$/).optional(), context: contextText });

export const postDraftOutput = z.object({ draft: z.string().max(280), characterCount: z.number().int().nonnegative().optional(), suggestedHashtags: hashtags, rationale: z.string().max(1000).default(''), warnings: warningList });
export const threadDraftOutput = z.object({ posts: z.array(z.object({ draft: z.string().max(280), characterCount: z.number().int().nonnegative().optional() })).min(1).max(20), summary: z.string().max(1500).default(''), warnings: warningList });
export const replyDraftOutput = postDraftOutput;
export const rewriteOutput = z.object({ draft: z.string().max(280), characterCount: z.number().int().nonnegative().optional(), changed: z.array(z.string().max(300)).max(20).default([]), warnings: warningList });
export const improveOutput = z.object({ original: z.string().max(12000), improvedDraft: z.string().max(280), whatChanged: z.array(z.string().max(300)).max(20).default([]), suggestedHashtags: hashtags, characterCount: z.number().int().nonnegative().optional(), warnings: warningList });
export const summaryOutput = z.object({ summary: z.string().max(5000), keyPoints: z.array(z.string().max(500)).max(30).default([]), participants: z.array(z.string().max(200)).max(100).default([]), importantClaims: z.array(z.string().max(500)).max(30).default([]), unresolvedPoints: z.array(z.string().max(500)).max(30).default([]), dataLimitations: z.array(z.string().max(500)).max(30).default([]) });
export const sentimentOutput = z.object({ overallSentiment: z.enum(['positive', 'negative', 'neutral', 'mixed']), confidence: z.number().min(0).max(1), positiveSignals: z.array(z.string().max(300)).max(20).default([]), negativeSignals: z.array(z.string().max(300)).max(20).default([]), neutralMixedSignals: z.array(z.string().max(300)).max(20).default([]), explanation: z.string().max(1500) });
export const ideasOutput = z.object({ ideas: z.array(z.object({ title: z.string().max(200), angle: z.string().max(500), description: z.string().max(1000), suggestedFormat: z.string().max(100), possibleHook: z.string().max(500), hashtags })).min(1).max(20) });
export const audienceOutput = z.object({ observedTopics: z.array(z.string().max(200)).max(30).default([]), engagementPatterns: z.array(z.string().max(500)).max(30).default([]), interactionCategories: z.array(z.string().max(300)).max(30).default([]), timingPatterns: z.array(z.string().max(300)).max(30).default([]), limitations: z.array(z.string().max(500)).max(30).default([]) });
export const trendOutput = z.object({ observed: z.string().max(1500), whyRelated: z.array(z.string().max(500)).max(30).default([]), keyTerms: z.array(z.string().max(200)).max(30).default([]), representativePatterns: z.array(z.string().max(500)).max(30).default([]), majorAccountsInSample: z.array(z.string().max(200)).max(30).default([]), limitations: z.array(z.string().max(500)).max(30).default([]) });
export const strategyOutput = z.object({ factsFromXData: z.array(z.string().max(500)).max(30).default([]), contentPillars: z.array(z.string().max(300)).max(20).default([]), postingIdeas: z.array(z.string().max(500)).max(30).default([]), formatRecommendations: z.array(z.string().max(300)).max(20).default([]), timingObservations: z.array(z.string().max(300)).max(20).default([]), engagementObservations: z.array(z.string().max(500)).max(20).default([]), experiments: z.array(z.string().max(500)).max(20).default([]), risksAndLimitations: z.array(z.string().max(500)).max(30).default([]) });
export const hashtagOutput = z.object({ recommendations: z.array(z.object({ hashtag: z.string().regex(/^#[A-Za-z0-9_]{1,100}$/), reason: z.string().max(500), category: z.string().max(100), sourceType: z.enum(['user_input', 'x_api', 'deterministic_analysis', 'mixed']) })).max(20), warnings: warningList });
export const calendarOutput = z.object({ entries: z.array(z.object({ day: z.string().max(40), date: z.string().max(40).optional(), contentIdea: z.string().max(500), format: z.string().max(100), draftConcept: z.string().max(280), recommendedTime: z.string().max(100).optional(), reason: z.string().max(500) })).min(1).max(155), warnings: warningList });
