'use client';

import { useEffect, useState } from 'react';
import { useTheme, useWidgetSDK } from '@nitrostack/widgets';

type Dict = Record<string, unknown>;
type Post = Dict & { id?: string; text?: string; author?: Dict; metrics?: Dict; createdAt?: string; media?: unknown[] };
type ToolCall = (name: string, args?: Dict) => Promise<unknown>;
type ExternalOpen = (url: string) => void;

function dict(value: unknown): Dict { return value && typeof value === 'object' && !Array.isArray(value) ? value as Dict : {}; }
function hasKey(value: Dict, key: string): boolean { return Object.prototype.hasOwnProperty.call(value, key); }
function list(value: unknown): unknown[] { return Array.isArray(value) ? value : []; }
function number(value: unknown): number { return typeof value === 'number' && Number.isFinite(value) ? value : 0; }
function string(value: unknown, fallback = ''): string { return typeof value === 'string' ? value : fallback; }
function displayMetric(value: unknown): string { return typeof value === 'number' && Number.isFinite(value) ? value.toLocaleString() : 'Unavailable'; }
function metric(post: Post, key: string): string { return displayMetric(dict(post.metrics)[key]); }
function hasHostValue(value: unknown): boolean { return value !== null && value !== undefined && (!(value && typeof value === 'object') || Object.keys(value as object).length > 0); }
function useHostToolData() {
  const sdk = useWidgetSDK();
  const [legacyOutput, setLegacyOutput] = useState<unknown>(null);
  const [legacyInput, setLegacyInput] = useState<unknown>(null);
  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      const data = event.data;
      if (!data || typeof data !== 'object') return;
      if (data.type === 'TOOL_OUTPUT' && data.data !== undefined) setLegacyOutput(data.data);
      if (data.type === 'NITRO_INJECT_OPENAI') {
        const globals = dict(data.data ?? data.openai);
        if (globals.toolOutput !== undefined) setLegacyOutput(globals.toolOutput);
        if (globals.toolInput !== undefined) setLegacyInput(globals.toolInput);
      }
    };
    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, []);
  const sdkOutput = sdk.getToolOutput<unknown>();
  const sdkInput = sdk.getToolInput<unknown>();
  return { sdk, output: hasHostValue(sdkOutput) ? sdkOutput : legacyOutput, input: hasHostValue(sdkInput) ? sdkInput : legacyInput };
}
function unwrapToolResult(value: unknown): Dict {
  const outer = dict(value);
  const structured = dict(outer.structuredContent);
  if (Object.keys(structured).length) return structured;
  if (typeof outer.result === 'string') {
    try { return dict(JSON.parse(outer.result)); } catch { return outer; }
  }
  const content = list(outer.content);
  const text = content.map((item) => dict(item).text).find((item): item is string => typeof item === 'string');
  if (text) { try { return dict(JSON.parse(text)); } catch { return { message: text }; } }
  return outer;
}
function actionError(value: unknown): string {
  const result = unwrapToolResult(value);
  if (result.isError === true || result.ok === false || typeof result.code === 'string') return string(result.message, string(result.code, 'Action unavailable.'));
  return '';
}
function useSafeActions(rawCallTool: ToolCall, rawOpenExternal?: ExternalOpen) {
  const [status, setStatus] = useState('');
  const [busy, setBusy] = useState(false);
  const callTool: ToolCall = async (name, args = {}) => {
    setBusy(true); setStatus('');
    try {
      const result = await rawCallTool(name, args);
      const error = actionError(result);
      setStatus(error || `${name} completed.`);
      return result;
    } catch (error) {
      const message = error instanceof Error ? error.message : 'The host could not complete that action.';
      setStatus(`${name} failed: ${message.replace(/\s+/g, ' ').slice(0, 240)}`);
      return { ok: false, code: 'WIDGET_ACTION_FAILED', message: 'The host could not complete that action.' };
    } finally { setBusy(false); }
  };
  const openExternal: ExternalOpen = (url) => {
    if (!rawOpenExternal) { setStatus('External navigation is unavailable in this host.'); return; }
    try { rawOpenExternal(url); setStatus('Opened in the host.'); } catch { setStatus('External navigation is unavailable in this host.'); }
  };
  return { callTool, openExternal, status, busy };
}
function Avatar({ user, label = 'X' }: { user: Dict; label?: string }) { const src = string(user.avatarUrl); return <div className="x-avatar">{src ? <img className="x-avatar-img" src={src} alt=""/> : string(user.name, label).slice(0, 1).toUpperCase()}</div>; }

export function WidgetFrame({ title, eyebrow, children }: { title: string; eyebrow?: string; children: React.ReactNode }) {
  const theme = useTheme();
  return <main className={`x-frame ${theme === 'dark' ? 'x-dark' : ''}`}><div className="x-brand"><span className="x-mark">𝕏</span><span>X Intelligence MCP</span></div>{eyebrow && <div className="x-eyebrow">{eyebrow}</div>}<h1>{title}</h1>{children}</main>;
}

export function WidgetData({ title, render }: { title: string | ((data: Dict, input: Dict) => string); render: (data: Dict, callTool: ToolCall, openExternal: ExternalOpen, toolInput: Dict) => React.ReactNode }) {
  const { sdk, output: hostOutput, input: hostInput } = useHostToolData();
  const { isReady, callTool: rawCallTool, openExternal: rawOpenExternal } = sdk;
  const actions = useSafeActions(rawCallTool, rawOpenExternal);
  const output = hostOutput;
  const toolInput = dict(hostInput);
  const fallbackTitle = typeof title === 'string' ? title : 'X Intelligence MCP';
  if (!isReady) return <WidgetFrame title={fallbackTitle}><div className="x-state"><span className="x-spinner" />Connecting to MCP…</div></WidgetFrame>;
  if (!output) return <WidgetFrame title={fallbackTitle}><div className="x-state"><div className="x-state-icon">◌</div><strong>Waiting for X data</strong><span>Run the linked MCP tool to populate this widget.</span></div></WidgetFrame>;
  const outputDict = unwrapToolResult(output);
  if (outputDict.ok === false || typeof outputDict.code === 'string' && ['AUTH_DISABLED', 'AUTH_REQUIRED', 'FORBIDDEN', 'BILLING_OR_ACCESS_RESTRICTED', 'RATE_LIMITED', 'AI_DISABLED', 'AI_NOT_CONFIGURED', 'AI_PROVIDER_UNAVAILABLE', 'AI_PROVIDER_AUTH_ERROR', 'AI_RATE_LIMITED', 'AI_TIMEOUT', 'AI_BAD_RESPONSE', 'AI_RESPONSE_INVALID', 'AI_CONTEXT_TOO_LARGE', 'AI_SAFETY_REFUSAL', 'AI_GROUNDING_FAILED'].includes(outputDict.code)) return <WidgetFrame title={fallbackTitle}><div className="x-state x-state-error"><div className="x-state-icon">!</div><strong>{string(outputDict.code, 'Request unavailable')}</strong><span>{string(outputDict.message, 'The requested data is not available in the current configuration.')}</span><span className="x-note">No mock data is shown.</span></div></WidgetFrame>;
  const frameTitle = typeof title === 'function' ? title(outputDict, toolInput) : title;
  return <WidgetFrame title={frameTitle}>{render(outputDict, actions.callTool, actions.openExternal, toolInput)}{actions.busy && <p role="status" className="x-note">Working…</p>}{actions.status && <p role="status" className="x-note">{actions.status}</p>}</WidgetFrame>;
}

function Button({ children, onClick, disabled = false, danger = false }: { children: React.ReactNode; onClick: () => void; disabled?: boolean; danger?: boolean }) { return <button type="button" className={danger ? 'x-button x-danger' : 'x-button'} onClick={onClick} disabled={disabled}>{children}</button>; }

function UserCard({ user }: { user: Dict }) {
  const metrics = dict(user.publicMetrics);
  const username = string(user.username, 'unknown');
  return <section className="x-card x-user"><Avatar user={user} label={username}/><div className="x-user-main"><div className="x-user-name">{string(user.name, username)} {user.verified === true && <span className="x-verified">✓</span>}</div><div className="x-muted">@{username}</div><p>{string(user.bio, 'No public bio available.')}</p><div className="x-stats"><span><b>{displayMetric(metrics.followers)}</b> followers</span><span><b>{displayMetric(metrics.following)}</b> following</span><span><b>{displayMetric(metrics.posts)}</b> posts</span></div></div></section>;
}

export function AccountProfileWidget() { return <WidgetData title="Account profile" render={(data, callTool, openExternal) => { const user = dict(data.user ?? data); const id = string(user.id); const username = string(user.username); return <><UserCard user={user}/><div className="x-actions"><Button disabled={!id} onClick={() => void callTool('x_get_user_posts', { userId: id, maxResults: 25 })}>View posts</Button><Button disabled={!id} onClick={() => void callTool('x_get_mentions', { userId: id, maxResults: 25 })}>Mentions</Button><Button disabled={!id} onClick={() => void callTool('x_get_followers', { userId: id, maxResults: 25 })}>Followers</Button><Button disabled={!id} onClick={() => void callTool('x_get_following', { userId: id, maxResults: 25 })}>Following</Button><Button disabled={!username} onClick={() => openExternal(`https://x.com/${encodeURIComponent(username)}`)}>View profile</Button></div></>; }}/>; }

export function PostCardWidget() { return <WidgetData title={(data) => { if (data.listType === 'followers') return 'Followers list'; if (data.listType === 'following') return 'Following list'; if (data.listType === 'user_posts') return 'User posts'; if (data.listType === 'mentions') return 'Mentions'; if (typeof data.summary === 'string') return 'Grounded summary'; if (Array.isArray(data.ideas)) return 'Content ideas'; if (Array.isArray(data.recommendations)) return 'Hashtag suggestions'; if (hasKey(data, 'factsFromXData')) return 'Content strategy'; if (hasKey(data, 'derivedMetric')) return 'Post analysis'; return 'Post'; }} render={(data, callTool, openExternal, input) => { if (data.listType === 'followers' || data.listType === 'following') return <UserListPanel data={data} callTool={callTool} openExternal={openExternal} input={input}/>; if (data.listType === 'user_posts' || data.listType === 'mentions') return <PostListPanel data={data} callTool={callTool} openExternal={openExternal} input={input}/>; if (typeof data.summary === 'string') return <SummaryCard data={data}/>; if (Array.isArray(data.ideas)) return <IdeasPanel data={data}/>; if (Array.isArray(data.recommendations)) return <HashtagPanel data={data}/>; if (hasKey(data, 'factsFromXData')) return <StrategyPanel data={data}/>; const nestedPost = dict(data.post); if (nestedPost.id || nestedPost.text) return <><PostCard post={nestedPost as Post} callTool={callTool} openExternal={openExternal}/>{hasKey(data, 'derivedMetric') && <EngagementPanel data={data}/>}</>; const post = dict(data) as Post; if (post.id || post.text) return <PostCard post={post} callTool={callTool} openExternal={openExternal}/>; return <GenericResult data={data}/>; }}/>; }

function SummaryCard({ data }: { data: Dict }) { const points = list(data.keyPoints); const participants = list(data.participants); const limitations = list(data.dataLimitations); return <section className="x-stack"><div className="x-card"><div className="x-section-title">Grounded summary</div><p className="x-post-text">{string(data.summary)}</p></div><TextList title="Key points" values={points}/><TextList title="Participants" values={participants}/>{limitations.length > 0 && <TextList title="Data limitations" values={limitations}/>}</section>; }
function TextList({ title, values }: { title: string; values: unknown[] }) { return <section className="x-card"><div className="x-section-title">{title}</div>{values.length ? <div className="x-metric-list">{values.slice(0, 10).map((value, index) => <div key={`${index}-${string(value)}`}><span>{string(value)}</span></div>)}</div> : <Empty text="Not available."/>}</section>; }
function GenericResult({ data }: { data: Dict }) { const serialized = JSON.stringify(data, null, 2); return <section className="x-card"><div className="x-section-title">Structured result</div><pre className="x-json">{serialized.length > 8000 ? `${serialized.slice(0, 8000)}\n…result truncated for display…` : serialized}</pre></section>; }
function PageControl({ toolName, input, data, callTool }: { toolName: string; input: Dict; data: Dict; callTool: ToolCall }) { const pagination = dict(data.pagination); const nextToken = string(pagination.nextToken); return nextToken ? <div className="x-actions"><Button onClick={() => void callTool(toolName, { ...input, paginationToken: nextToken })}>Next page</Button></div> : null; }
function PostListPanel({ data, callTool, openExternal, input }: { data: Dict; callTool: ToolCall; openExternal: ExternalOpen; input: Dict }) { const posts = list(data.data); const toolName = data.listType === 'mentions' ? 'x_get_mentions' : 'x_get_user_posts'; return <section className="x-stack"><div className="x-toolbar"><span className="x-pill">{posts.length} shown</span><span className="x-muted">Real X results · bounded page</span></div>{posts.length ? posts.map((item, index) => <PostCard key={string(dict(item).id, String(index))} post={dict(item) as Post} callTool={callTool} openExternal={openExternal}/>) : <Empty text="No posts in this page."/>}<PageControl toolName={toolName} input={input} data={data} callTool={callTool}/></section>; }
function UserListPanel({ data, callTool, openExternal, input }: { data: Dict; callTool: ToolCall; openExternal: ExternalOpen; input: Dict }) { const users = list(data.data); return <section className="x-stack"><div className="x-toolbar"><span className="x-pill">{users.length} shown</span><span className="x-muted">Real X accounts · bounded page</span></div>{users.length ? users.map((item, index) => { const user = dict(item); const id = string(user.id); const username = string(user.username); return <div className="x-card x-user-row" key={id || String(index)}><Avatar user={user} label={username}/><div><b>{string(user.name, 'Unknown')}</b><div className="x-muted">@{username || 'unknown'}</div></div><div className="x-actions"><Button disabled={!id} onClick={() => void callTool('x_get_user', { id })}>View profile</Button><Button disabled={!username} onClick={() => openExternal(`https://x.com/${encodeURIComponent(username)}`)}>Open X</Button></div></div>; }) : <Empty text="No accounts in this page."/>}<PageControl toolName={data.listType === 'following' ? 'x_get_following' : 'x_get_followers'} input={input} data={data} callTool={callTool}/></section>; }
function EngagementPanel({ data }: { data: Dict }) { const metric = dict(data.derivedMetric); return <section className="x-card"><div className="x-section-title">Derived engagement</div><div className="x-grid"><Stat label="Total engagement" value={displayMetric(metric.totalEngagement)}/><Stat label="Engagement rate" value={typeof metric.engagementRateByFollowers === 'number' ? `${metric.engagementRateByFollowers}%` : 'Unavailable'}/></div><p className="x-note">Derived locally from the real X post and available public metrics.</p></section>; }
function IdeasPanel({ data }: { data: Dict }) { const ideas = list(data.ideas); return <section className="x-stack">{ideas.slice(0, 20).map((item, index) => { const idea = dict(item); return <section className="x-card" key={`${string(idea.title, String(index))}-${index}`}><div className="x-section-title">{string(idea.title, `Idea ${index + 1}`)}</div><b>{string(idea.angle, 'Angle unavailable')}</b><p>{string(idea.description, 'Description unavailable')}</p><p className="x-note">Format: {string(idea.suggestedFormat, 'Unavailable')} · Hook: {string(idea.possibleHook, 'Unavailable')}</p><TextList title="Hashtags" values={list(idea.hashtags)}/></section>; })}</section>; }
function StrategyPanel({ data }: { data: Dict }) { return <section className="x-stack"><TextList title="Facts from X data" values={list(data.factsFromXData)}/><TextList title="Content pillars" values={list(data.contentPillars)}/><TextList title="Posting ideas" values={list(data.postingIdeas)}/><TextList title="Format recommendations" values={list(data.formatRecommendations)}/><TextList title="Timing observations" values={list(data.timingObservations)}/><TextList title="Engagement observations" values={list(data.engagementObservations)}/><TextList title="Experiments" values={list(data.experiments)}/><TextList title="Risks and limitations" values={list(data.risksAndLimitations)}/></section>; }
function HashtagPanel({ data }: { data: Dict }) { return <section className="x-stack">{list(data.recommendations).map((item, index) => { const recommendation = dict(item); return <section className="x-card" key={`${string(recommendation.hashtag, String(index))}-${index}`}><div className="x-section-title">{string(recommendation.hashtag, 'Hashtag unavailable')}</div><p>{string(recommendation.reason, 'No reason returned.')}</p><p className="x-note">Category: {string(recommendation.category, 'Unavailable')} · Source: {string(recommendation.sourceType, 'Unavailable')}</p></section>; })}<TextList title="Warnings" values={list(data.warnings)}/></section>; }

function PostCard({ post, callTool, openExternal }: { post: Post; callTool: ToolCall; openExternal: ExternalOpen }) { const author = dict(post.author); const media = dict(list(post.media)[0]); const [aiDraft, setAiDraft] = useState(''); const [aiStatus, setAiStatus] = useState(''); const id = string(post.id); const authorId = string(author.id); const authorUsername = string(author.username); const runDraft = async () => { setAiStatus('Generating draft…'); const result = unwrapToolResult(await callTool('x_generate_reply', { postId: id, tone: 'clear and useful' })); const draft = string(result.draft); setAiDraft(draft); setAiStatus(draft ? 'Reply draft ready for review.' : string(result.message, 'AI draft unavailable.')); }; return <article className="x-card x-post"><div className="x-post-head"><Button disabled={!authorId} onClick={() => void callTool('x_get_user', { id: authorId })}><Avatar user={author}/></Button><div><b>{string(author.name, 'Unknown author')}</b><div className="x-muted">@{authorUsername || 'unknown'} · {string(post.createdAt, 'time unavailable')}</div></div></div><p className="x-post-text">{string(post.text, 'No post text available.')}</p>{string(media.url, string(media.preview_image_url)) && <img className="x-post-media" src={string(media.url, string(media.preview_image_url))} alt={string(media.alt_text, 'Post media')}/>}<div className="x-post-metrics"><span>♥ {metric(post, 'likes')}</span><span>↻ {metric(post, 'reposts')}</span><span>↩ {metric(post, 'replies')}</span><span>❝ {metric(post, 'quotes')}</span></div><div className="x-actions"><Button disabled={!id} onClick={() => void callTool('x_analyze_post', { postId: id })}>Analyze</Button><Button disabled={!id} onClick={() => void callTool('x_analyze_sentiment', { postId: id })}>Sentiment</Button><Button disabled={!id} onClick={() => void runDraft()}>Generate reply draft</Button><Button disabled={!id} onClick={() => void callTool('x_summarize_thread', { postId: id, maxResults: 30 })}>Summarize thread</Button><Button disabled={!id} onClick={() => void callTool('x_summarize_conversation', { postId: id, maxResults: 30 })}>Summarize conversation</Button><Button disabled={!id} onClick={() => openExternal(`https://x.com/i/web/status/${encodeURIComponent(id)}`)}>Open post</Button><Button disabled={!authorUsername} onClick={() => openExternal(`https://x.com/${encodeURIComponent(authorUsername)}`)}>Open author</Button></div>{(aiDraft || aiStatus) && <section className="x-review"><div className="x-section-title">AI draft · review required</div>{aiDraft && <p className="x-post-text">{aiDraft}</p>}<p className="x-note">{aiStatus}</p></section>}</article>; }

export function PostFeedWidget() { return <WidgetData title="Post feed" render={(data, callTool, openExternal) => { const posts = list(data.data ?? data.posts); return <><div className="x-toolbar"><span className="x-pill">{posts.length} shown</span><span className="x-muted">Real X results · paginated sample</span></div>{posts.length ? <div className="x-stack">{posts.map((item, index) => <PostCard key={string(dict(item).id, String(index))} post={dict(item) as Post} callTool={callTool} openExternal={openExternal}/>)}</div> : <Empty text="No posts in this page."/>}</>; }}/>; }

export function SearchDashboardWidget() { return <WidgetData title="Search dashboard" render={(data, callTool, openExternal, input) => { const posts = list(dict(data.results ?? data).data ?? data.data); const pagination = dict(dict(data.results ?? data).pagination ?? data.pagination); const nextToken = string(pagination.nextToken); const authors = new Set(posts.map((item) => string(dict(dict(item).author).username)).filter(Boolean)); const hashtags = posts.flatMap((item) => list(dict(item).hashtags).map((tag) => string(tag))); return <><div className="x-grid"><Stat label="Results shown" value={posts.length}/><Stat label="Authors observed" value={authors.size}/><Stat label="Hashtags observed" value={hashtags.filter(Boolean).length}/></div><div className="x-section-title">Timeline</div>{posts.length ? <div className="x-stack">{posts.map((item, index) => <PostCard key={string(dict(item).id, String(index))} post={dict(item) as Post} callTool={callTool} openExternal={openExternal}/>)}</div> : <Empty text="No matching posts."/>}{nextToken && <div className="x-actions"><Button onClick={() => void callTool('x_search_posts', { ...input, paginationToken: nextToken })}>Load next page</Button></div>}</>; }}/>; }

function Stat({ label, value }: { label: string; value: number | string }) { return <div className="x-stat"><span>{label}</span><b>{typeof value === 'number' ? value.toLocaleString() : value}</b></div>; }
function Empty({ text }: { text: string }) { return <div className="x-empty">{text}</div>; }

export function AnalyticsDashboardWidget() { return <WidgetData title={(data) => hasKey(data, 'overallSentiment') ? 'Sentiment analysis' : hasKey(data, 'derivedMetric') ? 'Post analysis' : 'Analytics dashboard'} render={(data) => hasKey(data, 'overallSentiment') ? <SentimentAnalysisPanel data={data}/> : hasKey(data, 'derivedMetric') ? <EngagementPanel data={data}/> : (() => { const analytics = dict(data.analytics ?? data.derived); return <><div className="x-grid"><Stat label="Sample size" value={number(analytics.sampleSize)}/><Stat label="Avg engagement" value={displayMetric(analytics.averageEngagement)}/><Stat label="Avg likes" value={displayMetric(analytics.averageLikes)}/><Stat label="Avg impressions" value={displayMetric(analytics.averageImpressions)}/><Stat label="Posts / day" value={displayMetric(analytics.postingFrequencyPerDay)}/></div><MetricList title="Common hashtags" values={list(analytics.commonHashtags)}/><MetricList title="Active posting hours (UTC)" values={list(analytics.activePostingHours)}/><p className="x-note">Derived Metric · calculated locally from the returned X sample. Unavailable X metrics remain unavailable.</p></>; })()}/>; }
export function EngagementDashboardWidget() { return <WidgetData title="Engagement dashboard" render={(data) => { const analytics = dict(data.analytics ?? data.derivedMetric); return <><div className="x-grid"><Stat label="Likes" value={displayMetric(analytics.averageLikes)}/><Stat label="Replies" value={displayMetric(analytics.averageReplies)}/><Stat label="Reposts" value={displayMetric(analytics.averageReposts)}/><Stat label="Quotes" value={displayMetric(analytics.averageQuotes)}/></div><p className="x-note">Derived Metric · averages and totals are local calculations over the supplied sample.</p></>; }}/>; }
function MetricList({ title, values }: { title: string; values: unknown[] }) { return <section className="x-card"><div className="x-section-title">{title}</div>{values.length ? <div className="x-metric-list">{values.slice(0, 10).map((value, index) => { const row = dict(value); const label = string(row.hashtag, string(row.hourUtc, `#${index + 1}`)); return <div key={`${label}-${index}`}><span>{label}</span><b>{displayMetric(row.count ?? row.posts)}</b></div>; })}</div> : <Empty text="Not available in this sample."/>}</section>; }

function SentimentAnalysisPanel({ data }: { data: Dict }) { const sentiment = string(data.overallSentiment, 'unavailable'); const confidence = typeof data.confidence === 'number' ? `${Math.round(data.confidence * 100)}%` : 'Unavailable'; return <section className="x-stack"><div className="x-card x-status-card"><span className="x-status-dot"/><b>{sentiment.replaceAll('_', ' ')}</b><p>Text sentiment only · confidence {confidence}</p></div><div className="x-grid"><Stat label="Overall sentiment" value={sentiment}/><Stat label="Confidence" value={confidence}/><Stat label="Grounded" value={data.grounded === true ? 'Yes' : 'No'}/><Stat label="Source" value={string(data.sourceType, 'Unavailable')}/></div><TextList title="Positive signals" values={list(data.positiveSignals)}/><TextList title="Negative signals" values={list(data.negativeSignals)}/><TextList title="Neutral / mixed signals" values={list(data.neutralMixedSignals)}/><section className="x-card"><div className="x-section-title">Explanation</div><p className="x-post-text">{string(data.explanation, 'No explanation returned.')}</p><p className="x-note">Provider: {string(data.provider, 'Unavailable')} · Model: {string(data.model, 'Unavailable')}</p></section></section>; }

export function TrendDashboardWidget() { return <WidgetData title="Observed topic signals" render={(data) => { const signals = dict(data.signals ?? data.analysis ?? data); return <><div className="x-signal-banner">Observed Topic Signals <span>bounded search sample</span></div><MetricList title="Top hashtags" values={list(signals.topHashtags)}/><MetricList title="Top authors" values={list(signals.topAuthors)}/><p className="x-note">This view does not represent all of X and does not use an LLM.</p></>; }}/>; }
export function MentionsDashboardWidget() { return <PostFeedWidget/>; }
export function FollowersDashboardWidget() { return <WidgetData title="Followers" render={(data, callTool) => { const users = list(data.data ?? data.followers); return users.length ? <div className="x-stack">{users.map((item, index) => { const user = dict(item); return <div className="x-card x-user-row" key={string(user.id, String(index))}><div className="x-avatar">{string(user.name, 'X').slice(0, 1)}</div><div><b>{string(user.name, 'Unknown')}</b><div className="x-muted">@{string(user.username, 'unknown')}</div></div><Button onClick={() => void callTool('x_get_user', { id: string(user.id) })}>View</Button></div>; })}</div> : <Empty text="No accounts in this page."/>; }}/>; }

export function ComposerWidget() {
  const { sdk, output: hostOutput, input: hostInput } = useHostToolData();
  const { callTool: rawCallTool, openExternal: rawOpenExternal } = sdk;
  const { callTool, status: actionStatus, busy } = useSafeActions(rawCallTool, rawOpenExternal);
  const toolInput = dict(hostInput);
  const rawToolOutput = hostOutput;
  const toolOutput = unwrapToolResult(rawToolOutput);
  const isDraftResult = typeof toolOutput.draft === 'string' || typeof toolOutput.improvedDraft === 'string';
  const threadPosts = list(toolOutput.posts);
  const isThreadResult = threadPosts.length > 0 && threadPosts.every((post) => typeof dict(post).draft === 'string');
  const draftTitle = hasKey(toolInput, 'postId') || hasKey(toolInput, 'postText') ? 'AI Reply Draft' : hasKey(toolInput, 'text') ? 'AI Rewrite / Improve Draft' : 'AI Post Generator';
  const [text, setText] = useState('');
  const [stage, setStage] = useState<'draft' | 'review' | 'confirm'>('draft');
  const [status, setStatus] = useState('');
  const [confirmed, setConfirmed] = useState(false);
  const [aiStatus, setAiStatus] = useState('');
  const valid = text.trim().length > 0 && text.length <= 280;
  if (!sdk.isReady) return <WidgetFrame title="AI Post Generator"><div className="x-state"><span className="x-spinner" />Connecting to MCP…</div></WidgetFrame>;
  if (isAIError(toolOutput)) return <WidgetFrame title="AI Post Generator"><AIGenerationState data={toolOutput} input={toolInput} callTool={callTool}/></WidgetFrame>;
  if (isDraftResult) { const data = typeof toolOutput.draft === 'string' ? toolOutput : { ...toolOutput, draft: toolOutput.improvedDraft }; return <WidgetFrame title={draftTitle} eyebrow="DRAFT ONLY — NOTHING IS PUBLISHED AUTOMATICALLY"><AIPostDraftPanel data={data} callTool={callTool}/></WidgetFrame>; }
  if (isThreadResult) return <WidgetFrame title="AI Thread Generator" eyebrow="DRAFT ONLY — NOTHING IS PUBLISHED AUTOMATICALLY"><AIThreadDraftPanel data={toolOutput}/></WidgetFrame>;
  const generateDraft = async () => { setAiStatus('Generating draft…'); const result = unwrapToolResult(await callTool('x_generate_post', { topic: text.trim() || 'a useful update', goal: 'clear and useful', tone: 'clear and useful' })); const draft = string(result.draft); if (draft) { setText(draft); setStage('draft'); setConfirmed(false); setAiStatus('AI draft inserted. Review it before publishing.'); } else setAiStatus(string(result.message, 'AI draft unavailable.')); };
  const improveDraft = async () => { setAiStatus('Improving draft…'); const result = unwrapToolResult(await callTool('x_improve_post', { text: text.trim(), suggestHashtags: true })); const draft = string(result.improvedDraft); if (draft) { setText(draft); setStage('draft'); setConfirmed(false); setAiStatus('Improved draft inserted. Review it before publishing.'); } else setAiStatus(string(result.message, 'AI improvement unavailable.')); };
  const publish = async () => { setStatus('Publishing…'); const result = unwrapToolResult(await callTool('x_create_post', { text: text.trim(), confirm: true })); setStatus(result.isError === true || result.ok === false || result.code ? 'Publish failed. No success was claimed.' : 'Published to X.'); };
  return <WidgetFrame title="Compose post" eyebrow="EXPLICIT REAL X ACCOUNT ACTION"><div className="x-card"><div className="x-pill">{stage === 'draft' ? '1 · Draft' : stage === 'review' ? '2 · Review' : '3 · Confirm'}</div><textarea aria-label="Post draft" value={text} onChange={(event) => { setText(event.target.value); setStatus(''); setAiStatus(''); setStage('draft'); setConfirmed(false); }} placeholder="Write a draft…" maxLength={280}/><div className="x-actions"><Button disabled={busy} onClick={() => void generateDraft()}>Generate draft</Button><Button disabled={!valid || busy} onClick={() => void improveDraft()}>Improve draft</Button></div><div className="x-compose-footer"><span className={text.length > 280 ? 'x-count x-over' : 'x-count'}>{text.length}/280</span>{stage === 'draft' && <Button disabled={!valid} onClick={() => setStage('review')}>Review draft</Button>}{stage === 'review' && <><Button onClick={() => setStage('draft')}>Back</Button><Button disabled={!valid} onClick={() => setStage('confirm')}>Continue to confirm</Button></>}{stage === 'confirm' && <><Button onClick={() => setStage('review')}>Back</Button><label className="x-confirm-label"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)}/> I confirm this will publish to X.</label><Button disabled={!confirmed || busy} onClick={() => void publish()}>Publish</Button></>}</div>{stage !== 'draft' && <section className="x-card x-review"><div className="x-section-title">Final review</div><p className="x-post-text">{text.trim()}</p></section>}<p className="x-note">AI actions only insert drafts. Publishing is never automatic. The final tool call requires confirm=true and affects the configured real X account.</p>{aiStatus && <p role="status" className="x-note">{aiStatus}</p>}{status && <p role="status" className="x-note">{status}</p>}{actionStatus && <p role="status" className="x-note">{actionStatus}</p>}</div></WidgetFrame>;
}

const AI_ERROR_CODES = new Set(['AI_DISABLED', 'AI_NOT_CONFIGURED', 'AI_PROVIDER_UNAVAILABLE', 'AI_PROVIDER_AUTH_ERROR', 'AI_RATE_LIMITED', 'AI_TIMEOUT', 'AI_BAD_RESPONSE', 'AI_RESPONSE_INVALID', 'AI_CONTEXT_TOO_LARGE', 'AI_SAFETY_REFUSAL', 'AI_GROUNDING_FAILED']);
function isAIError(data: Dict): boolean { return data.ok === false || typeof data.code === 'string' && AI_ERROR_CODES.has(data.code); }
function AIGenerationState({ data, input, callTool }: { data: Dict; input: Dict; callTool: ToolCall }) {
  const code = string(data.code, 'AI_UNAVAILABLE');
  const rateLimited = code === 'AI_RATE_LIMITED';
  const title = rateLimited ? 'Generation rate limited' : code === 'AI_DISABLED' ? 'AI is disabled' : code === 'AI_NOT_CONFIGURED' ? 'AI provider not configured' : code === 'AI_RESPONSE_INVALID' ? 'Provider returned an invalid response' : 'AI generation unavailable';
  const message = rateLimited ? 'Groq temporarily rate-limited this request. Wait for the provider window to reset, then retry.' : string(data.message, 'The AI draft could not be generated.');
  return <div className="x-state x-state-error"><div className="x-state-icon">!</div><strong>{title}</strong><span>{message}</span>{rateLimited && <span className="x-note">No draft was fabricated. Retry explicitly when the provider is available.</span>}{string(input.topic) && <Button onClick={() => void callTool('x_generate_post', input)}>Retry generation</Button>}<span className="x-note">State: {code}. No X publication was attempted.</span></div>;
}
function AIPostDraftPanel({ data, callTool }: { data: Dict; callTool: ToolCall }) { const [draft, setDraft] = useState(string(data.draft)); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const copyDraft = async () => { try { await navigator.clipboard.writeText(draft); setStatus('Draft copied.'); } catch { setStatus('Copy is unavailable in this host.'); } }; const improveDraft = async () => { setBusy(true); setStatus('Improving draft…'); try { const result = unwrapToolResult(await callTool('x_improve_post', { text: draft, suggestHashtags: true })); if (typeof result.improvedDraft === 'string') { setDraft(result.improvedDraft); setStatus('Improved draft ready for review.'); } else setStatus(string(result.message, 'Improvement unavailable.')); } finally { setBusy(false); } }; return <section className="x-stack"><div className="x-card x-review"><div className="x-section-title">Generated draft</div><p className="x-post-text">{draft || 'No draft returned.'}</p><div className="x-grid"><Stat label="Characters" value={typeof data.characterCount === 'number' ? data.characterCount : draft.length}/><Stat label="Provider" value={string(data.provider, 'Unavailable')}/><Stat label="Model" value={string(data.model, 'Unavailable')}/><Stat label="Grounded" value={data.grounded === true ? 'Yes' : 'No'}/><Stat label="Source" value={string(data.sourceType, 'user_input')}/></div></div><div className="x-actions"><Button disabled={!draft || busy} onClick={() => void copyDraft()}>Copy draft</Button><Button disabled={!draft || busy} onClick={() => void improveDraft()}>Improve draft</Button></div><section className="x-card"><div className="x-section-title">Rationale</div><p>{string(data.rationale, 'No rationale returned.')}</p></section><TextList title="Suggested hashtags" values={list(data.suggestedHashtags)}/><TextList title="Warnings" values={list(data.warnings)}/>{status && <p role="status" className="x-note">{status}</p>}<p className="x-note">This is a draft only. Publishing is not available from x_generate_post.</p></section>; }
function AIThreadDraftPanel({ data }: { data: Dict }) { const posts = list(data.posts); return <section className="x-stack">{posts.map((item, index) => { const post = dict(item); const draft = string(post.draft); return <section className="x-card x-review" key={index}><div className="x-section-title">Post {index + 1} · {draft.length} characters</div><p className="x-post-text">{draft}</p></section>; })}<section className="x-card"><div className="x-section-title">Thread summary</div><p>{string(data.summary, 'No summary returned.')}</p></section><TextList title="Warnings" values={list(data.warnings)}/><p className="x-note">Thread output is draft-only and is not published automatically.</p></section>; }
function CapabilityRow({ label, available, write = false }: { label: string; available: unknown; write?: boolean }) { const enabled = available === true; return <div className="x-metric-list"><div><span>{label}</span><b>{enabled ? (write ? 'Write available' : 'Read available') : (write ? 'Write unavailable' : 'Unavailable')}</b></div></div>; }
function CapabilityPanel({ data }: { data: Dict }) { const authorization = dict(data.authorization); const readAccess = authorization.readAccess === true || data.readProfile === true || data.searchPosts === true; const writeAccess = authorization.writeAccess === true || data.createPost === true || data.deletePost === true || data.likePost === true || data.followUser === true || data.mediaUpload === true; return <section className="x-stack"><div className="x-card x-status-card"><span className={readAccess ? 'x-status-dot' : 'x-status-dot x-status-warn'}/><b>Capability / Authorization status</b><p>Read and write capabilities are derived from the current X credentials and authorization state.</p><div className="x-grid"><Stat label="Authentication mode" value={string(data.authenticationMode, 'none')}/><Stat label="X auth enabled" value={data.xAuthEnabled === true ? 'Yes' : 'No'}/><Stat label="Read access" value={readAccess ? 'Yes' : 'No'}/><Stat label="Write access" value={writeAccess ? 'Yes' : 'No'}/><Stat label="Authenticated" value={authorization.authenticated === true ? 'Yes' : 'No'}/><Stat label="OAuth configured" value={authorization.oauthConfigured === true ? 'Yes' : 'No'}/></div></div><section className="x-card"><div className="x-section-title">Read capabilities</div><CapabilityRow label="Profile lookup" available={data.readProfile}/><CapabilityRow label="Search posts" available={data.searchPosts}/><CapabilityRow label="Followers" available={data.readFollowers}/><CapabilityRow label="Following" available={data.readFollowing}/><CapabilityRow label="Mentions" available={data.readMentions}/></section><section className="x-card"><div className="x-section-title">Write capabilities</div><CapabilityRow label="Create post" available={data.createPost} write/><CapabilityRow label="Delete post" available={data.deletePost} write/><CapabilityRow label="Like post" available={data.likePost} write/><CapabilityRow label="Follow user" available={data.followUser} write/><CapabilityRow label="Media upload" available={data.mediaUpload} write/></section><p className="x-note">{writeAccess ? 'Write access is available only through explicit confirmation.' : 'READ AVAILABLE · WRITE UNAVAILABLE. X user OAuth is not connected.'}</p></section>; }
export function AuthorizationStatusWidget() { return <WidgetData title={(data) => hasKey(data, 'searchPosts') || hasKey(data, 'readProfile') ? 'Capability / Authorization status' : 'Authorization status'} render={(data, callTool) => { if (hasKey(data, 'searchPosts') || hasKey(data, 'readProfile')) return <CapabilityPanel data={data}/>; const status = dict(data.authorization ?? data); const state = string(status.state, 'not_configured'); const scopes = list(status.grantedScopes).map((scope) => string(scope)).filter(Boolean); const canDisconnect = state === 'oauth_connected' || state === 'token_expired'; return <><div className="x-card x-status-card"><span className={state === 'oauth_connected' ? 'x-status-dot' : 'x-status-dot x-status-warn'}/><b>{state.replaceAll('_', ' ')}</b><p>{status.authenticated === true ? 'An X user context is available to the server.' : 'No X user context is currently connected.'}</p><div className="x-grid"><Stat label="Read access" value={status.readAccess === true ? 'Yes' : 'No'}/><Stat label="Write access" value={status.writeAccess === true ? 'Yes' : 'No'}/><Stat label="Refresh available" value={status.refreshAvailable === true ? 'Yes' : 'No'}/></div></div><section className="x-card"><div className="x-section-title">Granted scopes</div>{scopes.length ? <div className="x-metric-list">{scopes.map((scope) => <div key={scope}><span>{scope}</span><b>Granted</b></div>)}</div> : <Empty text="No scopes reported."/>}<p className="x-note">Callback: {string(status.redirectUri, 'not configured')}</p>{canDisconnect && <Button danger onClick={() => void callTool('x_disconnect', { confirm: true })}>Disconnect locally</Button>}</section></>; }}/>; }
function ProviderRow({ provider }: { provider: Dict }) { return <div className="x-provider-row"><div><b>{string(provider.id, 'provider')}</b><div className="x-muted">Model: {string(provider.model, 'not configured')}</div></div><div className="x-provider-state">Configured: {provider.configured === true ? 'Yes' : 'No'} · Available: {provider.available === true ? 'Yes' : 'No'}</div><p className="x-note">{string(provider.message, provider.available === true ? 'Ready for AI requests.' : 'Not available in the current configuration.')}</p></div>; }
function AIStatusPanel({ data }: { data: Dict }) { const configured = list(data.configuredProviders).map((provider) => string(provider)).filter(Boolean); const providers = list(data.providers); const capabilities = list(data.capabilities).map((capability) => string(capability)).filter(Boolean); return <section className="x-stack"><div className="x-card x-status-card"><span className={data.enabled === true ? 'x-status-dot' : 'x-status-dot x-status-warn'}/><b>AI STATUS</b><p>Configuration-only provider status; no health generation request is performed.</p><div className="x-grid"><Stat label="AI enabled" value={data.enabled === true ? 'Yes' : 'No'}/><Stat label="Selected provider" value={string(data.selectedProvider, 'None')}/><Stat label="Selected model" value={string(data.selectedModel, 'None')}/><Stat label="Selection mode" value={string(data.selectionMode, 'auto')}/><Stat label="Grounding" value={data.groundingEnabled === true ? 'Enabled' : 'Disabled'}/></div></div><section className="x-card"><div className="x-section-title">Configured providers</div>{configured.length ? <div className="x-pill-row">{configured.map((provider) => <span className="x-pill" key={provider}>{provider}</span>)}</div> : <Empty text="No AI provider is configured."/>}{providers.map((provider, index) => <ProviderRow provider={dict(provider)} key={`${string(dict(provider).id, String(index))}-${index}`}/>)}</section><section className="x-card"><div className="x-section-title">Capabilities</div><div className="x-pill-row">{capabilities.map((capability) => <span className="x-pill" key={capability}>{capability.replaceAll('_', ' ')}</span>)}</div></section></section>; }
export function SystemStatusWidget() { return <WidgetData title={(data) => hasKey(data, 'selectedProvider') || hasKey(data, 'providers') ? 'AI status' : 'System status'} render={(data) => hasKey(data, 'selectedProvider') || hasKey(data, 'providers') ? <AIStatusPanel data={data}/> : <><div className="x-card x-status-card"><span className="x-status-dot"/> <b>{string(data.server, 'Connected')}</b><p>{string(data.message, 'Status received from the MCP server.')}</p></div><pre className="x-json">{JSON.stringify(data, null, 2)}</pre></>}/>; }
export function GenericStatusWidget({ title }: { title: string }) { return <WidgetData title={title} render={(data) => <><div className="x-card x-status-card"><span className="x-status-dot"/> <b>{string(data.server, 'Connected')}</b><p>{string(data.message, 'Status received from the MCP server.')}</p></div><pre className="x-json">{JSON.stringify(data, null, 2)}</pre></>}/>; }
export function ComparisonWidget() { return <WidgetData title="Account comparison" render={(data) => { const accounts = list(data.accounts); return <div className="x-stack">{accounts.map((item, index) => { const row = dict(item); return <div className="x-card" key={index}><UserCard user={dict(row.xProvided)}/><p className="x-note">Derived Metric sample size: {number(dict(row.derived).sampleSize)}</p></div>; })}</div>; }}/>; }
export function CalendarWidget() { return <WidgetData title="Content calendar" render={(data) => { const entries = list(data.entries); return entries.length ? <><div className="x-signal-banner">Planning calendar <span>draft concepts only · nothing scheduled</span></div><div className="x-stack">{entries.map((item, index) => { const entry = dict(item); return <section className="x-card" key={`${string(entry.date, string(entry.day, String(index)))}-${index}`}><div className="x-section-title">{string(entry.date, string(entry.day, 'Planned day'))}</div><b>{string(entry.contentIdea, 'Content idea unavailable')}</b><p className="x-post-text">{string(entry.draftConcept, 'Draft concept unavailable')}</p><div className="x-muted">Format: {string(entry.format, 'Unavailable')} · Recommended time: {string(entry.recommendedTime, 'Unavailable')}</div><p className="x-note">{string(entry.reason, 'No reason provided.')}</p></section>; })}</div><p className="x-note">Planning output only. This widget never schedules or publishes.</p></> : <Empty text="No generated calendar entries. Run x_generate_content_calendar to create a draft plan."/>; }}/>; }
