'use client';

import { useMemo, useState } from 'react';
import { useTheme, useWidgetSDK } from '@nitrostack/widgets';

type Dict = Record<string, unknown>;
type Post = Dict & { id?: string; text?: string; author?: Dict; metrics?: Dict; createdAt?: string; media?: unknown[] };

function dict(value: unknown): Dict { return value && typeof value === 'object' && !Array.isArray(value) ? value as Dict : {}; }
function list(value: unknown): unknown[] { return Array.isArray(value) ? value : []; }
function number(value: unknown): number { return typeof value === 'number' && Number.isFinite(value) ? value : 0; }
function string(value: unknown, fallback = ''): string { return typeof value === 'string' ? value : fallback; }
function displayMetric(value: unknown): string { return typeof value === 'number' && Number.isFinite(value) ? value.toLocaleString() : 'Unavailable'; }
function metric(post: Post, key: string): string { return displayMetric(dict(post.metrics)[key]); }
function Avatar({ user, label = 'X' }: { user: Dict; label?: string }) { const src = string(user.avatarUrl); return <div className="x-avatar">{src ? <img className="x-avatar-img" src={src} alt=""/> : string(user.name, label).slice(0, 1).toUpperCase()}</div>; }

export function WidgetFrame({ title, eyebrow, children }: { title: string; eyebrow?: string; children: React.ReactNode }) {
  const theme = useTheme();
  return <main className={`x-frame ${theme === 'dark' ? 'x-dark' : ''}`}><div className="x-brand"><span className="x-mark">𝕏</span><span>X Intelligence MCP</span></div>{eyebrow && <div className="x-eyebrow">{eyebrow}</div>}<h1>{title}</h1>{children}</main>;
}

export function WidgetData({ title, render }: { title: string; render: (data: Dict, callTool: (name: string, args?: Dict) => Promise<unknown>) => React.ReactNode }) {
  const { isReady, getToolOutput, callTool } = useWidgetSDK();
  const output = getToolOutput<unknown>();
  if (!isReady) return <WidgetFrame title={title}><div className="x-state"><span className="x-spinner" />Connecting to MCP…</div></WidgetFrame>;
  if (!output) return <WidgetFrame title={title}><div className="x-state"><div className="x-state-icon">◌</div><strong>Waiting for X data</strong><span>Run the linked MCP tool to populate this widget.</span></div></WidgetFrame>;
  const outputDict = dict(output);
  if (outputDict.ok === false || typeof outputDict.code === 'string' && ['AUTH_DISABLED', 'AUTH_REQUIRED', 'FORBIDDEN', 'BILLING_OR_ACCESS_RESTRICTED', 'RATE_LIMITED', 'AI_DISABLED', 'AI_NOT_CONFIGURED', 'AI_PROVIDER_UNAVAILABLE', 'AI_PROVIDER_AUTH_ERROR', 'AI_RATE_LIMITED', 'AI_TIMEOUT', 'AI_BAD_RESPONSE', 'AI_RESPONSE_INVALID', 'AI_CONTEXT_TOO_LARGE', 'AI_SAFETY_REFUSAL', 'AI_GROUNDING_FAILED'].includes(outputDict.code)) return <WidgetFrame title={title}><div className="x-state x-state-error"><div className="x-state-icon">!</div><strong>{string(outputDict.code, 'Request unavailable')}</strong><span>{string(outputDict.message, 'The requested data is not available in the current configuration.')}</span><span className="x-note">No mock data is shown.</span></div></WidgetFrame>;
  return <WidgetFrame title={title}>{render(dict(output), callTool)}</WidgetFrame>;
}

function Button({ children, onClick, disabled = false, danger = false }: { children: React.ReactNode; onClick: () => void; disabled?: boolean; danger?: boolean }) { return <button className={danger ? 'x-button x-danger' : 'x-button'} onClick={onClick} disabled={disabled}>{children}</button>; }

function UserCard({ user }: { user: Dict }) {
  const metrics = dict(user.publicMetrics);
  const username = string(user.username, 'unknown');
  return <section className="x-card x-user"><Avatar user={user} label={username}/><div className="x-user-main"><div className="x-user-name">{string(user.name, username)} {user.verified === true && <span className="x-verified">✓</span>}</div><div className="x-muted">@{username}</div><p>{string(user.bio, 'No public bio available.')}</p><div className="x-stats"><span><b>{displayMetric(metrics.followers)}</b> followers</span><span><b>{displayMetric(metrics.following)}</b> following</span><span><b>{displayMetric(metrics.posts)}</b> posts</span></div></div></section>;
}

export function AccountProfileWidget() { return <WidgetData title="Account profile" render={(data, callTool) => { const user = dict(data.user ?? data); return <><UserCard user={user}/><div className="x-actions"><Button onClick={() => void callTool('x_get_user_posts', { userId: string(user.id), maxResults: 25 })}>View posts</Button><Button onClick={() => void callTool('x_analyze_profile', { userId: string(user.id), maxResults: 50 })}>Analyze account</Button><Button onClick={() => void callTool('x_get_mentions', { userId: string(user.id), maxResults: 25 })}>Mentions</Button><Button onClick={() => void callTool('x_get_followers', { userId: string(user.id), maxResults: 25 })}>Followers</Button></div></>; }}/>; }

export function PostCardWidget() { return <WidgetData title="Post" render={(data, callTool) => { const post = dict(data.post ?? data) as Post; return <PostCard post={post} callTool={callTool}/>; }}/>; }

function PostCard({ post, callTool }: { post: Post; callTool: (name: string, args?: Dict) => Promise<unknown> }) { const author = dict(post.author); const media = dict(list(post.media)[0]); const [aiDraft, setAiDraft] = useState(''); const [aiStatus, setAiStatus] = useState(''); const runDraft = async () => { setAiStatus('Generating draft…'); const result = dict(await callTool('x_generate_reply', { postId: string(post.id), tone: 'clear and useful' })); const draft = string(result.draft); setAiDraft(draft); setAiStatus(draft ? 'Reply draft ready for review.' : string(result.message, 'AI draft unavailable.')); }; return <article className="x-card x-post"><div className="x-post-head"><Avatar user={author}/><div><b>{string(author.name, 'Unknown author')}</b><div className="x-muted">@{string(author.username, 'unknown')} · {string(post.createdAt, 'time unavailable')}</div></div></div><p className="x-post-text">{string(post.text, 'No post text available.')}</p>{string(media.url, string(media.preview_image_url)) && <img className="x-post-media" src={string(media.url, string(media.preview_image_url))} alt={string(media.alt_text, 'Post media')}/>}<div className="x-post-metrics"><span>♥ {metric(post, 'likes')}</span><span>↻ {metric(post, 'reposts')}</span><span>↩ {metric(post, 'replies')}</span><span>❝ {metric(post, 'quotes')}</span></div><div className="x-actions"><Button onClick={() => void callTool('x_analyze_post', { postId: string(post.id) })}>Analyze</Button><Button onClick={() => void callTool('x_analyze_sentiment', { postId: string(post.id) })}>Sentiment</Button><Button onClick={() => void runDraft()}>Generate reply draft</Button><Button onClick={() => void callTool('x_summarize_thread', { postId: string(post.id), maxResults: 30 })}>Summarize thread</Button><Button onClick={() => void callTool('x_summarize_conversation', { postId: string(post.id), maxResults: 30 })}>Summarize conversation</Button><Button onClick={() => void callTool('x_get_thread', { postId: string(post.id) })}>Thread</Button><Button onClick={() => void callTool('x_get_replies', { postId: string(post.id), maxResults: 25 })}>Replies</Button></div>{(aiDraft || aiStatus) && <section className="x-review"><div className="x-section-title">AI draft · review required</div>{aiDraft && <p className="x-post-text">{aiDraft}</p>}<p className="x-note">{aiStatus}</p></section>}</article>; }

export function PostFeedWidget() { return <WidgetData title="Post feed" render={(data, callTool) => { const posts = list(data.data ?? data.posts); return <><div className="x-toolbar"><span className="x-pill">{posts.length} shown</span><span className="x-muted">Real X results · paginated sample</span></div>{posts.length ? <div className="x-stack">{posts.map((item, index) => <PostCard key={string(dict(item).id, String(index))} post={dict(item) as Post} callTool={callTool}/>)}</div> : <Empty text="No posts in this page."/>}</>; }}/>; }

export function SearchDashboardWidget() { return <WidgetData title="Search dashboard" render={(data, callTool) => { const posts = list(dict(data.results ?? data).data ?? data.data); const authors = new Set(posts.map((item) => string(dict(dict(item).author).username))); const hashtags = posts.flatMap((item) => list(dict(item).hashtags).map((tag) => string(tag))); return <><div className="x-grid"><Stat label="Results shown" value={posts.length}/><Stat label="Authors observed" value={authors.size}/><Stat label="Hashtags observed" value={hashtags.filter(Boolean).length}/></div><div className="x-section-title">Timeline</div>{posts.length ? <div className="x-stack">{posts.map((item, index) => <PostCard key={string(dict(item).id, String(index))} post={dict(item) as Post} callTool={callTool}/>)}</div> : <Empty text="No matching posts."/>}</>; }}/>; }

function Stat({ label, value }: { label: string; value: number | string }) { return <div className="x-stat"><span>{label}</span><b>{typeof value === 'number' ? value.toLocaleString() : value}</b></div>; }
function Empty({ text }: { text: string }) { return <div className="x-empty">{text}</div>; }

export function AnalyticsDashboardWidget() { return <WidgetData title="Analytics dashboard" render={(data) => { const analytics = dict(data.analytics ?? data.derived); return <><div className="x-grid"><Stat label="Sample size" value={number(analytics.sampleSize)}/><Stat label="Avg engagement" value={displayMetric(analytics.averageEngagement)}/><Stat label="Avg likes" value={displayMetric(analytics.averageLikes)}/><Stat label="Avg impressions" value={displayMetric(analytics.averageImpressions)}/><Stat label="Posts / day" value={displayMetric(analytics.postingFrequencyPerDay)}/></div><MetricList title="Common hashtags" values={list(analytics.commonHashtags)}/><MetricList title="Active posting hours (UTC)" values={list(analytics.activePostingHours)}/><p className="x-note">Derived Metric · calculated locally from the returned X sample. Unavailable X metrics remain unavailable.</p></>; }}/>; }
export function EngagementDashboardWidget() { return <WidgetData title="Engagement dashboard" render={(data) => { const analytics = dict(data.analytics ?? data.derivedMetric); return <><div className="x-grid"><Stat label="Likes" value={displayMetric(analytics.averageLikes)}/><Stat label="Replies" value={displayMetric(analytics.averageReplies)}/><Stat label="Reposts" value={displayMetric(analytics.averageReposts)}/><Stat label="Quotes" value={displayMetric(analytics.averageQuotes)}/></div><p className="x-note">Derived Metric · averages and totals are local calculations over the supplied sample.</p></>; }}/>; }
function MetricList({ title, values }: { title: string; values: unknown[] }) { return <section className="x-card"><div className="x-section-title">{title}</div>{values.length ? <div className="x-metric-list">{values.slice(0, 10).map((value, index) => { const row = dict(value); const label = string(row.hashtag, string(row.hourUtc, `#${index + 1}`)); return <div key={`${label}-${index}`}><span>{label}</span><b>{displayMetric(row.count ?? row.posts)}</b></div>; })}</div> : <Empty text="Not available in this sample."/>}</section>; }

export function TrendDashboardWidget() { return <WidgetData title="Observed topic signals" render={(data) => { const signals = dict(data.signals ?? data.analysis ?? data); return <><div className="x-signal-banner">Observed Topic Signals <span>bounded search sample</span></div><MetricList title="Top hashtags" values={list(signals.topHashtags)}/><MetricList title="Top authors" values={list(signals.topAuthors)}/><p className="x-note">This view does not represent all of X and does not use an LLM.</p></>; }}/>; }
export function MentionsDashboardWidget() { return <PostFeedWidget/>; }
export function FollowersDashboardWidget() { return <WidgetData title="Followers" render={(data, callTool) => { const users = list(data.data ?? data.followers); return users.length ? <div className="x-stack">{users.map((item, index) => { const user = dict(item); return <div className="x-card x-user-row" key={string(user.id, String(index))}><div className="x-avatar">{string(user.name, 'X').slice(0, 1)}</div><div><b>{string(user.name, 'Unknown')}</b><div className="x-muted">@{string(user.username, 'unknown')}</div></div><Button onClick={() => void callTool('x_get_user', { id: string(user.id) })}>View</Button></div>; })}</div> : <Empty text="No accounts in this page."/>; }}/>; }

export function ComposerWidget() {
  const { callTool } = useWidgetSDK();
  const [text, setText] = useState('');
  const [stage, setStage] = useState<'draft' | 'review' | 'confirm'>('draft');
  const [status, setStatus] = useState('');
  const [confirmed, setConfirmed] = useState(false);
  const [aiStatus, setAiStatus] = useState('');
  const valid = text.trim().length > 0 && text.length <= 280;
  const generateDraft = async () => { setAiStatus('Generating draft…'); const result = dict(await callTool('x_generate_post', { topic: text.trim() || 'a useful update', goal: 'clear and useful', tone: 'clear and useful' })); const draft = string(result.draft); if (draft) { setText(draft); setStage('draft'); setConfirmed(false); setAiStatus('AI draft inserted. Review it before publishing.'); } else setAiStatus(string(result.message, 'AI draft unavailable.')); };
  const improveDraft = async () => { setAiStatus('Improving draft…'); const result = dict(await callTool('x_improve_post', { text: text.trim(), suggestHashtags: true })); const draft = string(result.improvedDraft); if (draft) { setText(draft); setStage('draft'); setConfirmed(false); setAiStatus('Improved draft inserted. Review it before publishing.'); } else setAiStatus(string(result.message, 'AI improvement unavailable.')); };
  const publish = async () => { setStatus('Publishing…'); const result = dict(await callTool('x_create_post', { text: text.trim(), confirm: true })); setStatus(result.isError === true || result.ok === false ? 'Publish failed. No success was claimed.' : 'Published to X.'); };
  return <WidgetFrame title="Compose post" eyebrow="EXPLICIT REAL X ACCOUNT ACTION"><div className="x-card"><div className="x-pill">{stage === 'draft' ? '1 · Draft' : stage === 'review' ? '2 · Review' : '3 · Confirm'}</div><textarea aria-label="Post draft" value={text} onChange={(event) => { setText(event.target.value); setStatus(''); setAiStatus(''); setStage('draft'); setConfirmed(false); }} placeholder="Write a draft…" maxLength={280}/><div className="x-actions"><Button onClick={() => void generateDraft()}>Generate draft</Button><Button disabled={!valid} onClick={() => void improveDraft()}>Improve draft</Button></div><div className="x-compose-footer"><span className={text.length > 280 ? 'x-count x-over' : 'x-count'}>{text.length}/280</span>{stage === 'draft' && <Button disabled={!valid} onClick={() => setStage('review')}>Review draft</Button>}{stage === 'review' && <><Button onClick={() => setStage('draft')}>Back</Button><Button disabled={!valid} onClick={() => setStage('confirm')}>Continue to confirm</Button></>}{stage === 'confirm' && <><Button onClick={() => setStage('review')}>Back</Button><label className="x-confirm-label"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)}/> I confirm this will publish to X.</label><Button disabled={!confirmed} onClick={() => void publish()}>Publish</Button></>}</div>{stage !== 'draft' && <section className="x-card x-review"><div className="x-section-title">Final review</div><p className="x-post-text">{text.trim()}</p></section>}<p className="x-note">AI actions only insert drafts. Publishing is never automatic. The final tool call requires confirm=true and affects the configured real X account.</p>{aiStatus && <p role="status" className="x-note">{aiStatus}</p>}{status && <p role="status" className="x-note">{status}</p>}</div></WidgetFrame>;
}
export function AuthorizationStatusWidget() { return <WidgetData title="Authorization status" render={(data, callTool) => { const status = dict(data.authorization ?? data); const state = string(status.state, 'not_configured'); const scopes = list(status.grantedScopes).map((scope) => string(scope)).filter(Boolean); const canDisconnect = state === 'oauth_connected' || state === 'token_expired'; return <><div className="x-card x-status-card"><span className={state === 'oauth_connected' ? 'x-status-dot' : 'x-status-dot x-status-warn'}/><b>{state.replaceAll('_', ' ')}</b><p>{status.authenticated === true ? 'An X user context is available to the server.' : 'No X user context is currently connected.'}</p><div className="x-grid"><Stat label="Read access" value={status.readAccess === true ? 'Yes' : 'No'}/><Stat label="Write access" value={status.writeAccess === true ? 'Yes' : 'No'}/><Stat label="Refresh available" value={status.refreshAvailable === true ? 'Yes' : 'No'}/></div></div><section className="x-card"><div className="x-section-title">Granted scopes</div>{scopes.length ? <div className="x-metric-list">{scopes.map((scope) => <div key={scope}><span>{scope}</span><b>Granted</b></div>)}</div> : <Empty text="No scopes reported."/>}<p className="x-note">Callback: {string(status.redirectUri, 'not configured')}</p>{canDisconnect && <Button danger onClick={() => void callTool('x_disconnect', { confirm: true })}>Disconnect locally</Button>}</section></>; }}/>; }
export function GenericStatusWidget({ title }: { title: string }) { return <WidgetData title={title} render={(data) => <><div className="x-card x-status-card"><span className="x-status-dot"/> <b>{string(data.server, 'Connected')}</b><p>{string(data.message, 'Status received from the MCP server.')}</p></div><pre className="x-json">{JSON.stringify(data, null, 2)}</pre></>}/>; }
export function ComparisonWidget() { return <WidgetData title="Account comparison" render={(data) => { const accounts = list(data.accounts); return <div className="x-stack">{accounts.map((item, index) => { const row = dict(item); return <div className="x-card" key={index}><UserCard user={dict(row.xProvided)}/><p className="x-note">Derived Metric sample size: {number(dict(row.derived).sampleSize)}</p></div>; })}</div>; }}/>; }
export function CalendarWidget() { return <WidgetData title="Content calendar" render={(data) => { const entries = list(data.entries); return entries.length ? <><div className="x-signal-banner">Planning calendar <span>draft concepts only · nothing scheduled</span></div><div className="x-stack">{entries.map((item, index) => { const entry = dict(item); return <section className="x-card" key={`${string(entry.date, string(entry.day, String(index)))}-${index}`}><div className="x-section-title">{string(entry.date, string(entry.day, 'Planned day'))}</div><b>{string(entry.contentIdea, 'Content idea unavailable')}</b><p className="x-post-text">{string(entry.draftConcept, 'Draft concept unavailable')}</p><div className="x-muted">Format: {string(entry.format, 'Unavailable')} · Recommended time: {string(entry.recommendedTime, 'Unavailable')}</div><p className="x-note">{string(entry.reason, 'No reason provided.')}</p></section>; })}</div><p className="x-note">Planning output only. This widget never schedules or publishes.</p></> : <Empty text="No generated calendar entries. Run x_generate_content_calendar to create a draft plan."/>; }}/>; }
